  #Note: This parameters are meant for trajectory node
Fr  : 200   #frequency
x_waypoints : [0, 0, 0, 0] #x coordinates for end effector
y_waypoints : [-0.2, 0.2, -0.50, 0.2]  #y coordinates for end effector
z_waypoints : [-0.18, 0.2, -0.18, 0.2] #z coordinates for end effector
time : [] #corresponding time for coordinates of end effector


ax_waypoints : [0.82, 0.93, 0.76, 0.66] #x coordinates for end effector
ay_waypoints : [0.57, 0.22, -0.20, -0.29]  #y coordinates for end effector
az_waypoints : [-0.06, 0.13, 0.03, -0.10] #z coordinates for end effector